### ISSUE TITLE
elenai dodge bar disappears after eating

### ISSUE THREAD

**Issue by Meskino** [camcamcamcamcam/mindful-eating#1]
basically when you eat any type of food the elenai dodge bar disappears or rather the midnful eating sprites overlap with the elenai dodge sprites i think...

**Comment by ContentCrisis** [comment]
Can confirm this with other mods as well. When the custom bar triggers, my water bar also disappears (from the Water Source mod).

**Comment by camcamcamcamcam** [comment]
Fixed in next release - I was cancelling all future GUI changes instead of just the ones I needed to
