### ISSUE TITLE
Suspicious Stew whole stack get consumed instead of single item

### ISSUE THREAD

**Issue by ItoKyoshiro** [camcamcamcamcam/mindful-eating#10]
Hi!
Love this mod but encountered this issue and not sure why it's happening but when you try to consume a whole stack (16) of Suspicious Stew you get them "transformed" into a single Bowl and lose the whole stack instead of only consuming one.
This behaviour is totally different with the Mushroom Stew, Beetroot Soup or Rabbit Stew which all behave as intended: consume with the whole stack in hand (16) but only use one and get a bowl which get stacked on your inventory.
My guess it's something related with Suspicious Stew having an specific NBT tagged with them but don't know exactly why only missbehave with this one :(

**Comment by camcamcamcamcam** [comment]
Ok this is fixed on the version I just uploaded to curseforge
