### ISSUE TITLE
Eating ungrouped foods cause the hunger bar invisible

### ISSUE THREAD

**Issue by masonclomid** [camcamcamcamcam/mindful-eating#15]
The problem with eating ungrouped foods causing the hunger bar to disappear is still not solved, even also the bubble bar disappear after I eat the vegetables from the [Pizzacraft](https://www.curseforge.com/minecraft/mc-mods/pizzacraft)  mod, and the two bars cann't be restore.
Another, when config is set to Diet compatible, Iogically the hunger bar should show the food group with the highest points and apply the corresponding bonus, but in reality the hunger bar still shows the previous meal and apply the bonus of all groups as long as its points aren't 0.

**Comment by ManaStar** [comment]
What version are you playing on?

**Comment by masonclomid** [comment]
I'm playing on version 1.16, forge 36.2.39, using the latest version of mindful, pizzacraft, and diet

**Comment by ManaStar** [comment]
I'm quite late, but should be fixed in 1.1.1!
