### ISSUE TITLE
[ SERVER : Issue ] java.lang.Exception: Mod Loading has failed

### ISSUE THREAD

**Issue by zndrmn** [camcamcamcamcam/mindful-eating#2]
### **[ SERVER : Issue ] java.lang.Exception: Mod Loading has failed**
_Latest.log / Line 56 : [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers.
The latest version of Abnormals Core and Diet are installed_
- - -
MC **: 1.16.5**
Java **: 1.8.0_311**
Forge **: 36.2.8**
Mod Name **: mindful-eating-1.16.5-1.0.0**
- - -
Crash Report **: https://gist.github.com/zndrmn/bb0c19ca87b417621b1b45a2467ac414#file-gistfile1-txt**
Debug.log **: https://gist.github.com/zndrmn/1444387fe1d83cb4e0c3a89d2e1e3939#file-gistfile1-txt**
Latest.log **: https://gist.github.com/zndrmn/8e0064521b0d81b3ff594dd037b2dcdb#file-gistfile1-txt**

**Comment by camcamcamcamcam** [comment]
Forgot to specify Only in Client in the Subscriber, should be fixed in the next build which I will upload soon
