### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Nyancatpig** [camcamcamcamcam/mindful-eating#4]
Upon starting a server with this mod installed, it crashes with this message.

Failure message: Mindful Eating (mindful_eating) has failed to load correctly
                java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist

**Comment by xXTerrarianXx** [comment]
Same issue.
[crash-2021-12-07_10.52.34-fml.txt](https://github.com/camcamcamcamcam/mindful-eating/files/7670121/crash-2021-12-07_10.52.34-fml.txt)

**Comment by camcamcamcamcam** [comment]
Should be fixed in next release
