### ISSUE TITLE
Suggestion - Compatibility with the Classic Bars mod

### ISSUE THREAD

**Issue by SheReyy** [camcamcamcamcam/mindful-eating#5]
Hi there! I'm working on an expert style modpack for 1.16.5. I feel like your mod would really benefit the feeling that I'm going for in my pack, but I think it would fit even more if your mod was compatible with Classic Bars, which I'm using in my pack. It would be amazing if the food icon there would change, like it does with the vanilla hunger bar.

![image](https://user-images.githubusercontent.com/91336389/145515418-0156dcbe-472b-4f91-a392-0edde78696db.png)

**Comment by camcamcamcamcam** [comment]
Since this mod is intended to be vanilla style, I don't intend to add special compatibility with Classic Bars which appears to cater to modded

**Comment by camcamcamcamcam** [comment]
Since this mod is intended to be vanilla style, I don't intend to add special compatibility with Classic Bars which appears to cater to less vanilla style ideas like having higher than maximum armour and health.

I'll definitely consider any pull requests that add it for me though!
